glass_client_id: <%= Rails.application.secrets.glass_client_id %>
glass_client_secret: <%= Rails.application.secrets.glass_client_secret %>
GOOGLE_SUBSCRIPTION_PROXY: 'https://mirrornotifications.appspot.com/forward?url='
hostname: 'refract-145367.use1-2.nitrousbox.com'
bridge_wan_ip: <%= Rails.application.secrets.bridge_wan_ip %>
