GLASS_CLIENT_ID: '340178224882-gejge6l6rkqcak4al516ejt0b74a86oc.apps.googleusercontent.com'
GLASS_CLIENT_SECRET: 'ENw5yRh_ncCVgJ-BG7V4kjnZ'
GOOGLE_SUBSCRIPTION_PROXY: 'https://mirrornotifications.appspot.com/forward?url='
HOSTNAME: 'http://dg.willjasen.com:3000'
