GLASS_CLIENT_ID: 435863930723-5kbkucavfnuhh3egd796b9e6ltdtt7qj.apps.googleusercontent.com
GLASS_CLIENT_SECRET: P7mPkMnEnONcli2oB9-58GBl
GOOGLE_SUBSCRIPTION_PROXY: https://mirrornotifications.appspot.com/forward?url=
HOSTNAME: http://dg.willjasen.com:3000
