GLASS_CLIENT_ID: 340178224882-ar7mmkuihlnv0uqlt9mfd5rjbjmv76q0.apps.googleusercontent.com
GLASS_CLIENT_SECRET: 0yeD1x4eMpcsM4O_4uYsd9ok
GOOGLE_SUBSCRIPTION_PROXY: https://mirrornotifications.appspot.com/forward?url=
HOSTNAME: http://dg.willjasen.com:3000
