# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1501c39cf015e50a6827e80d6eee679bf0bd1fc6713c7e4cfd36a995be2b9e4a7d8464a812bb1839c875591f153bd1df08644420f5f28362fb8dbb967b2b2d
  glass_client_id: 340178224882-iqlpcj49aa56q9j53l9hjge3v76e5mja.apps.googleusercontent.com
  glass_client_secret: vyUYluez14QW4hFM8y69Oans
  bridge_wan_ip: willjasen-wznqpmrwgg.dynamic-m.com

test:
  secret_key_base: ea9b41fdd83294120ff7f657d8f5aaa2c081d98b3159c1dddb34d4a9058bb26da60fc8943eacd9ceff8d098dea6a06f9356a6c479463ba174c39bc12e1114d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
